CREATE TABLE USERS(
    ID_NUMBER VARCHAR(20) NOT NULL,
    ID_TYPE VARCHAR(1) NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    SECONDNAME VARCHAR(255) NOT NULL,
    SURNAME VARCHAR(255) NOT NULL,
    SECONDSURNAME VARCHAR(255) NOT NULL,
    PHONE VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255) NOT NULL,
    CITYOFRESIDENCE VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID_NUMBER)
);